SELECT * FROM ACIONISTAS

/**
UPDATE
ACIONISTAS
SET CARGO ='08-CONSELHEIRO DE ADMINISTRAÇÃO'
WHERE CARGO='08-CONSELHEIRO DE ADMINISTRAÃ§Ã£O'
**/



SELECT * FROM ATIVIDADE_PRINCIPAL;

/**

UPDATE
ATIVIDADE_PRINCIPAL 
SET DESCRICAO ='HOLDINGS DE INSTITUIÇÕES NÃO-FINANCEIRAS'
WHERE DESCRICAO='HOLDINGS DE INSTITUIÃ§ÃµES NÃ£O-FINANCEIRAS'

UPDATE
ATIVIDADE_PRINCIPAL 
SET DESCRICAO ='HOLDINGS DE INSTITUIÇÕES NÃO FINANCEIRAS'
WHERE DESCRICAO='HOLDINGS DE INSTITUIÇÕES NÃO-FINANCEIRAS'


UPDATE
ATIVIDADE_PRINCIPAL 
SET DESCRICAO ='OUTRAS ATIVIDADES DE SERVIÇOS PRESTADOS PRINCIPALMENTE AS EMPRESAS NÃO ESPECIFICADAS ANTERIORMENTE'
WHERE DESCRICAO='OUTRAS ATIVIDADES DE SERVIÃ§OS PRESTADOS PRINCIPALMENTE Ã S EMPRESAS NÃ£O ESPECIFICADAS ANTERIORMENTE'

UPDATE
ATIVIDADE_PRINCIPAL 
SET DESCRICAO ='DESENVOLVIMENTO E LICENCIAMENTO DE PROGRAMAS DE COMPUTADOR CUSTOMIZÁVEIS'
WHERE DESCRICAO='DESENVOLVIMENTO E LICENCIAMENTO DE PROGRAMAS DE COMPUTADOR CUSTOMIZÃ¡VEIS'

UPDATE
ATIVIDADE_PRINCIPAL 
SET DESCRICAO ='DESENVOLVIMENTO E LICENCIAMENTO DE PROGRAMAS DE COMPUTADOR NÃO CUSTOMIZÁVEIS'
WHERE DESCRICAO='DESENVOLVIMENTO E LICENCIAMENTO DE PROGRAMAS DE COMPUTADOR NÃ£O-CUSTOMIZÃ¡VEIS'

**/

TRUNCATE TABLE ACIONISTAS
TRUNCATE TABLE EMPRESA_DESAFIO
TRUNCATE TABLE ATIVIDADE_PRINCIPAL