SELECT * FROM [dbo].[ACIONISTAS] ORDER BY NOME
SELECT * FROM [dbo].[ATIVIDADE_PRINCIPAL]
SELECT * FROM [dbo].[EMPRESA_DESAFIO]



SELECT * FROM 



CREATE VIEW QUANTIDADE_SOCIO
AS
SELECT 
ac.nome,
count(ac.nome) as Qtd_aparece
FROM ACIONISTAS AC 
INNER JOIN EMPRESA_DESAFIO EMP ON AC.CNPJ = EMP.CNPJ
--WHERE QTD_APARECE >1
group by ac.nome
HAVING count(ac.nome) >1
--ORDER BY 1
